```{r}
library(cowplot)
library(ggplot2)
library(reshape2)
library(kknn)
library(pROC)
library(datasets)
```

```{r}
iris_data<-read.table(file = './iris.txt', sep = "", header = TRUE)
clus_data<-iris_data[c(1,2,3,4)]
clus_data<-scale(clus_data)
head(clus_data)
```

```{r,include=FALSE}
# pkgs <- c("factoextra",  "NbClust")
# install.packages(pkgs)
library(ggplot2)
library(factoextra)
library(NbClust)
library(parameters)
```

```{r}
# Elbow method
fviz_nbclust(clus_data, kmeans, method = "wss") +
    geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")

# Silhouette method
fviz_nbclust(clus_data, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")

# Gap statistic
# nboot = 50 to keep the function speedy. 
# recommended value: nboot= 500 for your analysis.
# Use verbose = FALSE to hide computing progression.
set.seed(123)
fviz_nbclust(clus_data, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
```


```{r}
n_clust<-n_clusters(data.frame(clus_data),package = c("easystats", "NbClust", "mclust"),standardize=FALSE)
data.frame(clus_data)
n_clust
#n_clust
```